# Generated by Django 6.0.1 on 2026-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(default="Other", max_length=50),
        ),
    ]
